spring:

    web:
      locale: ko_KR
    servlet:
      encoding:
        force: true
        enabled: true
        charset: UTF-8

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false

    datasource:
      url: jdbc:mysql://localhost:3306/server_monitoring
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: tagtag1010
