spring:
    ai:
      mcp:
        server:
          type: sse # WebFlux
          sse:
            path: /mcp/message # MCP
    web:
      locale: ko_KR
    servlet:
      encoding:
        force: true
        enabled: true
        charset: UTF-8


logging:
  file:
    name: app/logs/mcp.log
  level:
    root: INFO
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"  # logfile은 위험하니 제거
  endpoint:
    health:
      show-details: always    # 인증될 경우에만 가능