spring:
    web:
      locale: ko_KR
    servlet:
      encoding:
        force: true
        enabled: true
        charset: UTF-8

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false

    datasource:
      url: ${DB_URL}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    mvc:
      async:
        request-timeout: 300000

    ai:
      mcp:
        server:
          protocol: STATELESS
          name: SpringServerDoctor
          version: 1.0.0
          capabilities:
            tool: true
            resource: false
            prompt: false
            completion: false

          stateless:
            mcp-endpoint: /mcp

openai:
  api-key: ${OPENAI_API_KEY}

forwarder:
  image-url : ${FORWARDER_IMAGE_URL}

