spring:
    web:
      locale: ko_KR
    servlet:
      encoding:
        force: true
        enabled: true
        charset: UTF-8

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false

    datasource:
      url: ${DB_URL}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

openai:
  api-key: ${OPENAI_API_KEY}
mcp :
  server-url : ${AWS_URL}